apiVersion: v1

kind: Service

metadata: 
  name: {{ .Values.userservice.name }}-clusterip-service

spec: 
  type: {{ .Values.userservice.service.type }}
  ports: 
    - port: 80
      targetPort: {{ .Values.userservice.image.exposedPort }}

  selector: 
    server: {{ .Values.userservice.name }}